opengallerysurvey/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('survey.urls'))
]

survey/urls.py
from django.urls import path

from survey import views

urlpatterns = [
    path('survey/<int:survey_id>/', views.survey),
    path('survey/<int:survey_id>/done/', views.survey_done)
]

survey/models.py
from django.db import models


class Survey(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title


class SurveyQuestion(models.Model):
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    topic = models.CharField(max_length=50)

    TYPE_CHOICES = (
        ('SELECT', 'select'),
        ('RADIO', 'radio'),
        ('CHECKBOX', 'checkbox'),
    )
    type = models.CharField(
        max_length=50,
        choices=TYPE_CHOICES,
    )

    required = models.BooleanField()

    choice_limit = models.PositiveSmallIntegerField()

    def __str__(self):
        return self.topic


class Option(models.Model):
    question = models.ForeignKey(SurveyQuestion, on_delete=models.CASCADE)
    text = models.CharField(max_length=50)

    def __str__(self):
        return self.text


class SurveyResponse(models.Model):
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=15)

    def __str__(self):
        return self.survey.title + ' 응답 결과 #' + str(self.id)


class SurveyQuestionResponse(models.Model):
    survey_response = models.ForeignKey(SurveyResponse, on_delete=models.CASCADE)
    topic = models.CharField(max_length=50)
    selected_options = models.ManyToManyField(Option)

    def __str__(self):
        return self.topic

survey/views.py
from typing import List

from django.http import HttpRequest
from django.shortcuts import render, redirect

from survey.models import *


def survey(request: HttpRequest, survey_id: int):
    selected_survey = Survey.objects.get(id=survey_id)
    if request.method == 'POST':
        question_response_dict = {}
        survey_response = SurveyResponse(survey=selected_survey)
        for name, input_list in request.POST.lists():
            if name == 'csrfmiddlewaretoken':
                continue

            if name == 'tel':
                survey_response.phone_number = input_list[0]
                continue

            question = SurveyQuestion.objects.get(id=name)

            if len(input_list) > question.choice_limit:
                return render(request, 'survey.html', {
                    'survey': selected_survey,
                    'error': f'선택 가능한 숫자를 넘었습니다. (문항: {question.topic})',
                })
            if question.required and len(input_list) < 1:
                return render(request, 'survey.html', {
                    'survey': selected_survey,
                    'error': f'필수 선택 문항이 입력되지 않았습니다. (문항: {question.topic})',
                })

            def get_options(option_id_list: List[str]):
                return question.option_set.filter(id__in=option_id_list)

            survey_question_response = SurveyQuestionResponse(survey_response=survey_response, topic=question.topic)
            options = get_options(input_list)
            question_response_dict[question.id] = survey_question_response, options
        survey_response.save()
        for question_id in question_response_dict:
            response = question_response_dict[question_id][0]
            response.save()
            response_options = question_response_dict[question_id][1]
            response.selected_options.add(*response_options)
            response.save()
        return redirect(survey_done, survey_id=survey_id)

    else:
        return render(request, 'survey.html', {'survey': selected_survey})


def survey_done(request: HttpRequest, survey_id: int):
    selected_survey = Survey.objects.get(id=survey_id)
    return render(request, 'survey-done.html', {'survey': selected_survey})

survey/templates/checkbox-field.html
<div class="field">
    <label class="label">
        {{ title }}
        {% if required == True %}
            *
        {% endif %}
    </label>
    {% for item in items %}
        <div class="control">
            <label class="checkbox">
                <input type="checkbox" value={{ item.id }} name="{{ name }}">
                {{ item }}
            </label>
        </div>
    {% endfor %}
</div>

survey/templates/input-tel-field.html
<div class="field">
    <label class="label">
        {{ title }}
        {% if required == True %}
            *
        {% endif %}
    </label>
    <label class="control">
        <input class="input" type="tel" name="tel" placeholder={{ placeholder }} required={{ required }}>
    </label>
</div>

survey/templates/radio-field.html
<div class="field">
    <label class="label">
        {{ title }}
        {% if required == True %}
            *
        {% endif %}
    </label>
    {% for item in items %}
        <div class="control">
            <label class="radio">
                <input type="radio" value={{ item.id }} name="{{ name }}" required={{ required }}>
                {{ item }}
            </label>
        </div>
    {% endfor %}
</div>

survey/templates/select-field.html
<div class="field">
    <label class="label">
        {{ title }}
        {% if required == True %}
            *
        {% endif %}
    </label>
    <div class="control">
        <label class="select">
            <select required={{ required }} name="{{ name }}">
                <option value="" disabled selected>{{ placeholder }}</option>
                {% for item in items %}
                    <option value={{ item.id }}>{{ item }}</option>
                {% endfor %}
            </select>
        </label>
    </div>
</div>

survey/templates/survey-done.html
{% extends 'base.html' %}

{% block title %}
    {{ survey.title }} 완료
{% endblock %}

{% block content %}
    <section class="hero is-fullheight is-info">
        <div class="hero-body">
            <div class="">
                <p class="title">
                    {{ survey.title }} 완료
                </p>
                <p class="subtitle">
                    수고하셨습니다.
                </p>
            </div>
        </div>
    </section>
{% endblock %}

survey/templates/survey.html
{% extends 'base.html' %}

{% block content %}
    <div class="container is-max-desktop">
        <form class="box m-3" method="post">
            {% csrf_token %}
            <h1 class="title">
                {{ survey.title }}
            </h1>
            {% for question in survey.surveyquestion_set.all %}
                {% if question.type == 'SELECT' %}
                    {% include 'select-field.html' with title=question.topic name=question.id items=question.option_set.all required=question.required %}
                {% endif %}
                {% if question.type == 'RADIO' %}
                    {% include 'radio-field.html' with title=question.topic name=question.id items=question.option_set.all required=question.required %}
                {% endif %}
                {% if question.type == 'CHECKBOX' %}
                    {% include 'checkbox-field.html' with title=question.topic name=question.id items=question.option_set.all required=question.required %}
                {% endif %}
            {% endfor %}
            {% include 'input-tel-field.html' with title="전화번호 입력" placeholder="010-0000-0000" required=True %}
            <div class="field mt-5">
                <div class="control is-flex is-justify-content-end">
                    <button class="button is-link" type="submit">
                        제출
                    </button>
                </div>
            </div>
        </form>
    </div>

    {% if error %}
        <div class="notification is-danger is-light mx-6">
            <button class="delete"></button>
            {{ error }}
        </div>
        <script>
            document.addEventListener('DOMContentLoaded', () => {
                (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
                    const $notification = $delete.parentNode;
                    $delete.addEventListener('click', () => {
                        $notification.parentNode.removeChild($notification);
                    });
                });
            });
        </script>
    {% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
            Open Gallery Survey App
        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>